language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - PINS="cf.dev:. cf-lwt.dev:."
matrix:
  include:
    - os: osx
      env: OCAML_VERSION=4.07 PACKAGE="cf"
    - os: osx
      env: OCAML_VERSION=4.08 PACKAGE="cf-lwt"
